name: ci

on:
  push:
    branches:
      - "*"  # run for branches
    tags:
      - "*"  # run for tags
  pull_request:
    branches:
      - "*"  # run for branches
    tags:
      - "*"  # run for tags

jobs:
  test:
    defaults:
      run:
        working-directory: go/src/github.com/microservices-demo/user
    runs-on: ubuntu-latest
    env:
      GROUP: f3lin
      USERNAME: f3lin
      COMMIT: ${{ github.sha }}
      REPO_USER: user
      REPO_USER_DB: user-db
      GO_VERSION: 1.7.5
      GOPATH: /home/runner/work/user/user/go

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          path: go/src/github.com/microservices-demo/user

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Setup PATH
        run: echo "${GOPATH}/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          make deps
          wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2_amd64.deb
          sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2_amd64.deb

      - name: Install/Downgrade MongoDB to version 3.6
        run: |
          wget -qO - https://pgp.mongodb.com/server-3.6.asc | sudo tee /etc/apt/trusted.gpg.d/mongodb-org-3.6.gpg
          echo "deb [trusted=yes arch=amd64] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/3.6 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.6.list
          sudo apt-get update
          sudo apt-get install -y --allow-downgrades mongodb-org=3.6.20 mongodb-org-server=3.6.20 mongodb-org-shell=3.6.20 mongodb-org-mongos=3.6.20 mongodb-org-tools=3.6.20 || echo "Error is misleading, it was successfully installed"     

      #      - name: Install/Downgrade MongoDB to version 3.6
      #        run: |
      #          wget -qO - https://www.mongodb.org/static/pgp/server-3.6.asc | sudo apt-key add -
      #          echo "deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/3.6 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.6.list
      #          sudo apt-get update
      #          sudo apt-get install -y --allow-downgrades mongodb-org=3.6.20 mongodb-org-server=3.6.20 mongodb-org-shell=3.6.20 mongodb-org-mongos=3.6.20 mongodb-org-tools=3.6.20 || echo "Error is misleading, it was successfully installed"

      - name: Unit Tests
        run: glide novendor| xargs go test -v

      #      - name: Create cover profile
      #        run: make coverprofile

      - name: Run Docker Test
        run: make dockertest

      #      - name: Submit Coveralls
      #        env:
      #          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #        run: goveralls -coverprofile=cover.profile -service=github

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.USERNAME }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Automatic Tagging of Releases
        id: increment-git-tag
        run: |
          chmod +x scripts/git_update_tag.sh
          bash scripts/git_update_tag.sh -v patch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push user to Docker Hub
        id: build-push-image
        env:
          IMAGE_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
        run: |
          cd docker/user
          docker build -t $GROUP/$REPO_USER:$IMAGE_TAG .
          docker push $GROUP/$REPO_USER:$IMAGE_TAG

      - name: Push user to Docker Hub
        id: build-push-image
        env:
          IMAGE_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
        run: |
          cd docker/user-db
          docker build -t $GROUP/$REPO_USER:$IMAGE_TAG .
          docker push $GROUP/$REPO_USER_DB:$IMAGE_TAG

#      # Push to dockerhub
#      - name: Push user to Docker Hub
#        uses: docker/build-push-action@v6
#        if: startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/main'
#        with:
#          push: true
#          file: docker/user/Dockerfile-release
#          tags: ${{ env.GROUP }}/${{ env.REPO }}:latest
#          #          path: go/src/github.com/microservices-demo/user
##          tag_with_ref: true
##          tag_with_sha: true
#
#      - name: Push user-db to Docker Hub
#        uses: docker/build-push-action@v6
#        if: startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/main'
#        with:
#          push: true
#          file: docker/user-db/Dockerfile
#          tags: ${{ env.GROUP }}/${{ env.REPO }}:latest
##          path: go/src/github.com/microservices-demo/user/docker/user-db
##          tag_with_ref: true
##          tag_with_sha: true
